spring.application.name=banking1

server.port=10001


spring.datasource.url=jdbc:mysql://localhost:3306/npcibatch6
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto = update

eureka.CLient.serviceUrl.defaultZone=http://localhost:9000/eureka

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=npci12345
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=springboot

